services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test-tier
    depends_on:
      mssql:
        condition: service_healthy

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: aYAJX1WhrK2B%6OUXN8MKR_oj
    networks:
      - test-tier
    healthcheck:
      test: |-
        /opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -C -N -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  test-tier: